version: '3.5'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    networks:
      - thesis_network
  minio_mc:
    container_name: minio_mc
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./models:/media
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/saved-images;
      /usr/bin/mc mb minio/saved-models;
      /usr/bin/mc anonymous set public minio/saved-images;
      /usr/bin/mc anonymous set public minio/saved-models;
      /usr/bin/mc cp -r /media/ minio/saved-models;
      "
    networks:
      - thesis_network
  tensorflow-serving:
      image: tensorflow/serving:2.6.2
      container_name: tensorflow-serving
      hostname: tensorflow-serving
      restart: unless-stopped
      ports:
        - "8500:8500"
        - "8501:8501"
      depends_on:
        - minio
        - minio_client
        - mongodb
      environment:
        S3_ENDPOINT: http://minio:9000
        AWS_ACCESS_KEY_ID: minio
        AWS_SECRET_ACCESS_KEY: minio123
        MODEL_BASE_PATH: s3://saved-models
        MODEL_NAME: inceptionv3
      networks:
        - thesis_network
  flask_app:
    container_name: flask_app
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
       FLASK_ENV: dev
       FLASK_APP: main.py
       FLASK_RUN_HOST: 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    depends_on:
      - tensorflow-serving
      - mongodb
      - minio_client
      - minio
    networks:
      - thesis_network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGO_INITDB_ROOT_PASSWORD: root_pwd
      MONGO_DB_NAME: image_data
    ports:
      - "27017:27017"
    networks:
      - thesis_network

networks:
  thesis_network:
    name: thesis_app_network